[package]
name = "gandiva_rust_udf_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", features = [] }
serde_json = "1.0.111"
serde = { version = "1.0.64", features = ["derive"] }
libc = "0.2.141"